Unify the usage of "serverURL" option
1Password/connect-sdk-js pull request #13
Opened 2021-04-28 13:33 UTC by petetnt

This PR is a small fix for the parameter usage, unifying `serverUrl`, `BaseURL`, `ServerURL`, `token` and `Token` to `serverURL`. Using the current instructions (on JavaScript files, TypeScript catches it), users will run into a bit of an confusing error `BaseURL and token are required` if the user copies the 

```
const op = OnePasswordConnect({
	serverUrl: "http://localhost:8000",
	token: "my-token",
	keepAlive: true,
});
```

example from the README.md

2021-05-03 16:27 UTC, verkaufer requested changes
Thanks for consolidating these! Can you fix the the message thrown from the client constructor? It still says `serverUrl` instead of the capitalized `serverURL`.

Otherwise this is good to go.

2021-05-03 16:27 UTC, verkaufer commented on src/lib/op-connect.ts
> +        throw new Error("Options serverUrl and token are required.");
```suggestion
        throw new Error("Options serverURL and token are required.");
```

2021-05-04 08:07 UTC, jpcoenen approved these changes

2021-05-04 15:07 UTC, verkaufer approved these changes

2021-05-04 15:12 UTC, merged

2021-05-04 21:16 UTC, petetnt commented
hey, thanks for fixing https://github.com/1Password/connect-sdk-js/pull/13#pullrequestreview-650509611 :) I was out-of-office for the past few days. 

Keep up the good work!