Feat/add search by title
1Password/connect-sdk-js pull request #79
Opened 2022-08-25 08:29 UTC by ephremAddiss

We, at [Addis](https://addissoftware.com/), are integrating 1Password to our enterprise application and we want to add a feature that search all items that contains a given title value.

2022-09-08 17:45 UTC, volodymyrZotov commented
@ephremAddiss Thank you very much for the contribution and for helping us to become better. 👍 
Such an ability is already done within [here](https://github.com/1Password/connect-sdk-js/pull/70).

It will be available in the next release. We are going to make it soon.

2022-09-15 11:25 UTC, ephremAddiss commented
@volodymyrZotov I have checked the new release and i am afraid it doesn't include the functionality i proposed. It uses title exact match, what i am proposing is contains based title. It would make more sense to search for certain values in the title than remembering exact matching.

Could you please have a look at it?

Thanks

2022-09-15 14:26 UTC, volodymyrZotov commented
@ephremAddiss Hello. 
Ok, I see. I'll take a closer look into the PR, thanks.

2022-09-16 09:12 UTC, volodymyrZotov requested changes

2022-09-16 09:12 UTC, volodymyrZotov commented on __test__/op-connect.test.ts
> +        const getItemsByTitleMock = (title: string) => nock(mockServerUrl)
You can use the `apiMock.listItemsByTitleSearch` method that you've created instead.

2022-09-16 09:12 UTC, volodymyrZotov commented on __test__/op-connect.test.ts
> +        const getFullItemMock = (itemId: string) =>
you can use `apiMock.getItemById` instead

2022-09-16 09:12 UTC, volodymyrZotov commented on src/lib/resources.ts
> +      public async listItemsByTitleSearch(
Let's rename to `listItemsByTitleContains`

2022-09-16 09:12 UTC, volodymyrZotov commented on src/lib/resources.ts
> +     * @param {string} itemTitle
```suggestion
     * @param {string} titleSearchStr
```

2022-09-16 09:12 UTC, volodymyrZotov commented on src/lib/op-connect.ts
> +        title: string,
```suggestion
        titleSearchStr: string,
```

2022-09-16 09:12 UTC, volodymyrZotov commented on src/lib/op-connect.ts
> +     * @param {string} title
```suggestion
     * @param {string} titleSearchStr
```

2022-09-16 09:12 UTC, volodymyrZotov commented on src/lib/resources.ts
> +      public async listItemsByTitleSearch(
Please put this method below `listItemsByTitle`

2022-09-16 09:12 UTC, volodymyrZotov commented on src/lib/resources.ts
> +     * Search by title for all Items which contains a given title.
```suggestion
     * Search for the Items in which the Title contains a provided string.
```

2022-09-16 09:12 UTC, volodymyrZotov commented on src/lib/resources.ts
> +     *  If found, queries for complete item details and returns results
```suggestion
```

2022-09-16 09:12 UTC, volodymyrZotov commented on src/lib/utils/query-builder.ts
> +export const searchByTitle = (title: string): string => buildFilterQuery(coByTitle(title));
Please add an empty line at the end of the file.

2022-09-16 17:55 UTC, ephremAddiss commented
Done. And @volodymyrZotov Thanks for all the suggestions and improvement.

2022-09-19 11:34 UTC, ephremAddiss reviewed
@volodymyrZotov  I have resolved the changes you have requested. Have a look and give me a feedback.
Thanks.

2022-09-19 12:14 UTC, volodymyrZotov commented on __test__/op-connect.test.ts
> +        // Search all items by title which contains  the given value `title`
```suggestion
```

2022-09-19 12:16 UTC, volodymyrZotov commented on __test__/op-connect.test.ts
> +        // Search all items by title which contains  the given value `title`
@ephremAddiss Please remove this comment. I think the test case description is self-descriptive enough.

2022-09-19 12:17 UTC, volodymyrZotov commented
Hi @ephremAddiss . Well done! Looks very good. Thank you! 👍

2022-09-20 08:40 UTC, volodymyrZotov approved these changes

2022-09-20 08:46 UTC, volodymyrZotov commented
@ephremAddiss Hi. I've just noticed that your commits are not signed. Please sign them in order to be able to merge.
You can create another PR with the same changes and signed commits. Or do it in a way that's easier for you.

2022-09-20 13:11 UTC, ephremAddiss commented
@volodymyrZotov  Hello, I have used `git rebase` to sign my prev commits and i have managed to change some but other commits are hard to change since i have merged some changes from your previous release.

Is it possible to merge on the current state or should i start from scratch? thanks

2022-09-20 13:16 UTC, volodymyrZotov commented
@ephremAddiss I can't merge if there are unsigned commits.

2022-09-20 13:25 UTC, ephremAddiss commented
Okay, I will start from scratch.

2022-09-21 10:37 UTC, closed without merging

2022-09-21 11:19 UTC, volodymyrZotov commented
Implemented here #82 as this branch contains unsigned commits.